language: python

python:
  - 3.5

before_install:
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Travis CI"

install:
  - pip install -r requirements.txt

script:
  - py.test publisher-test.py
